### ISSUE TITLE
Cannot present AI chat modal again after closing it by clicking the top-right close button once

### ISSUE THREAD

**Issue by ZihaoGuan** [Forethought-Technologies/solve-ios#4]
Hi,

When running the demo project on iOS device,  we encountered an issue where the chat modal cannot be fully loaded and presented again if user has dismissed it by clicking the top-right close button as shown below.

![Simulator Screen Recording - iPhone 13 - 2022-05-31 at 10 24 52](https://user-images.githubusercontent.com/14171285/171064564-d57c26e5-20f5-4d96-86d3-016ef3035ee6.gif)

However if user tries to drag down to dismiss the modal, it can be presented again.

![Simulator Screen Recording - iPhone SE (2nd generation) - 2022-05-31 at 10 34 45](https://user-images.githubusercontent.com/14171285/171065044-2a1f92e3-13dc-4d3a-95b5-76752b99049f.gif)

**Comment by mknippen** [comment]
We're actively looking into this. It appears to be a server-side issue. I'll report back when I have more information.

**Comment by mknippen** [comment]
This turned out to be a backend issue caching the close command. This has been fixed on the server-side, with no changes being needed on the client.
